[[app]]
    id = 1
    name = "Chiropt√®res"
    base_url = "suivi_chiro/site"
    appId = 101
    img = "img/chiro.png"

    [[app.menu]]
    url = "#/suivi_chiro/site"
    config_url = "config?app=suivi_chiro&vue=site&vue=list"
    data_url = "suivi_chiro/sites"
    label = "Suivi"
    restrict = 2

    [[app.menu]]
    url = "#/suivi_chiro/inventaire"
    label = "Inventaire"
    config_url = "config?app=suivi_chiro&vue=visite&vue=list_ssite"
    restrict = 2

[[app]]
    id = 2
    name = "TEST"
    base_url = "#/suivi_chiro/site"
    appId = 100
    img = "img/chiro.png"
